/**
 * Vendors a curated slice of simple-icons into `src/lib/brand-icons.generated.ts`.
 *
 * BUILD TIME, not runtime. The app's promise is on its own footer — *"your data
 * never leaves this Mac"* — and it ships a nonce CSP with no image or font host
 * beyond the app itself. Fetching a logo per merchant would break both, and
 * would also mean the calendar renders differently with the network down. So the
 * paths are baked into a TypeScript module and tree-shaken like any other code.
 *
 * simple-icons is CC0-1.0 (public domain), which is why this is vendorable at
 * all; the brand marks themselves remain their owners' trademarks and are used
 * here only to identify the merchant a charge came from, which is nominative use.
 *
 * ⚠️ The list is CURATED, not "everything". simple-icons ships 3,453 marks and
 * the ledger holds 893 merchants; baking all of either would be ~1MB of paths to
 * serve two dozen recurring series. Everything unmatched falls back to a
 * monogram tile, which is not a degraded case — see `brand-icon-match.ts`.
 *
 * Run: pnpm brand-icons
 */
import fs from "node:fs";
import path from "node:path";
import * as simpleIcons from "simple-icons";

/**
 * Slugs worth carrying, chosen from what a personal ledger in the US actually
 * repeats: streaming, telecoms, ride-hailing, delivery, the card networks and
 * the banks this app already imports from.
 *
 * Several obvious ones are absent from simple-icons 16 and cannot be added here
 * — Amazon, OpenAI, T-Mobile, Walmart, Xfinity and most US utilities were all
 * removed upstream over trademark policy. They monogram, and that is fine.
 */
const WANTED = [
  // streaming / subscriptions
  "netflix", "spotify", "youtube", "youtubemusic", "audible", "steam", "playstation",
  "patreon", "twitch", "crunchyroll", "duolingo", "coursera", "udemy",
  // software the owner actually pays for
  "apple", "github", "notion", "figma", "dropbox", "googledrive", "icloud",
  "adobeacrobatreader", "jetbrains", "linear", "slack", "zoom",
  // transport / delivery / food
  "uber", "ubereats", "lyft", "doordash", "instacart", "grubhub", "starbucks",
  "mcdonalds", "chipotle", "dominos", "pizzahut", "kfc", "subway", "dunkin",
  // retail
  "target", "ikea", "etsy", "ebay", "shopify", "nike", "adidas", "zara", "uniqlo",
  // money
  "chase", "discover", "americanexpress", "visa", "mastercard", "paypal", "venmo",
  "zelle", "robinhood", "wellsfargo", "bankofamerica", "coinbase", "cashapp",
  "wise", "revolut", "stripe",
  // fuel / travel
  "shell", "tesla", "airbnb", "delta", "americanairlines",
  "marriott", "hilton",
] as const;

interface Emitted {
  slug: string;
  title: string;
  hex: string;
  path: string;
}

function exportNameFor(slug: string): string {
  return `si${slug.charAt(0).toUpperCase()}${slug.slice(1)}`;
}

const registry = simpleIcons as unknown as Record<
  string,
  { title: string; hex: string; path: string; slug?: string } | undefined
>;

const found: Emitted[] = [];
const missing: string[] = [];
for (const slug of WANTED) {
  const icon = registry[exportNameFor(slug)];
  if (!icon) {
    missing.push(slug);
    continue;
  }
  found.push({ slug, title: icon.title, hex: icon.hex, path: icon.path });
}
found.sort((a, b) => a.slug.localeCompare(b.slug));

const body = found
  .map(
    (i) =>
      `  ${JSON.stringify(i.slug)}: { title: ${JSON.stringify(i.title)}, hex: ${JSON.stringify(
        i.hex,
      )}, path: ${JSON.stringify(i.path)} },`,
  )
  .join("\n");

const out = `// GENERATED by scripts/generate-brand-icons.ts — do not edit by hand.
// Source: simple-icons (CC0-1.0). Brand marks remain their owners' trademarks
// and are used here only to identify the merchant behind a charge.
// Regenerate with: pnpm brand-icons

export interface BrandIcon {
  /** the brand's own name, used as the mark's accessible label */
  title: string;
  /** the brand's official hex, WITHOUT the leading # */
  hex: string;
  /** a single SVG path in a 24×24 viewBox */
  path: string;
}

/**
 * Declared "as const satisfies Record<string, BrandIcon>" rather than as a plain
 * Record: it keeps the KEYS as literals, so BrandSlug is a closed union and a
 * lookup by one is total. That turns "this fragment maps to a slug nobody
 * vendored" from a runtime fall-through — which looks exactly like a deliberate
 * monogram — into a compile error.
 */
export const BRAND_ICONS = {
${body}
} as const satisfies Record<string, BrandIcon>;

export type BrandSlug = keyof typeof BRAND_ICONS;
`;

const target = path.join(process.cwd(), "src", "lib", "brand-icons.generated.ts");
fs.writeFileSync(target, out);
console.log(
  `wrote ${found.length} brand icons → ${path.relative(process.cwd(), target)}` +
    (missing.length ? `\nnot in simple-icons (will monogram): ${missing.join(", ")}` : ""),
);
